import { Clock3, X } from 'lucide-react';
import { useState } from 'react';
import AttendanceStatusBadge from './AttendanceStatusBadge.jsx';

const fieldClassName = 'mt-1.5 w-full rounded-md border border-[#dfe6f0] bg-white px-3 py-2.5 text-sm text-[#101828] outline-none focus:border-[#6659f5] focus:ring-2 focus:ring-[#ecebff]';
const Detail = ({ label, value }) => <div><p className="text-xs font-medium text-[#667085]">{label}</p><p className="mt-1 text-sm text-[#101828]">{value}</p></div>;
const timeOptions = Array.from({ length: 144 }, (_, index) => { const hour = Math.floor(index / 12) % 12 || 12; const minute = String((index % 12) * 5).padStart(2, '0'); return `${String(hour).padStart(2, '0')}:${minute}`; });
const toTimeParts = (value) => { const [time = '09:00', period = 'AM'] = value === '-' ? [] : value.split(' '); return { time, period }; };
const toMinutes = (time, period) => { const [hours, minutes] = time.split(':').map(Number); return ((hours % 12) + (period === 'PM' ? 12 : 0)) * 60 + minutes; };
const calculateWorkingHours = (checkInTime, checkInPeriod, checkOutTime, checkOutPeriod) => { let duration = toMinutes(checkOutTime, checkOutPeriod) - toMinutes(checkInTime, checkInPeriod); if (duration < 0) duration += 24 * 60; return `${Math.floor(duration / 60)}h ${String(duration % 60).padStart(2, '0')}m`; };
const TimeSelector = ({ label, time, period, onTimeChange, onPeriodChange }) => <label className="block text-sm font-medium text-[#344767]">{label}<span className="mt-1.5 grid grid-cols-[minmax(0,1fr)_4.5rem] gap-2"><select className={`${fieldClassName} mt-0 w-full`} value={time} onChange={(event) => onTimeChange(event.target.value)}>{timeOptions.map((option) => <option key={option}>{option}</option>)}</select><select className={`${fieldClassName} mt-0 w-full`} value={period} onChange={(event) => onPeriodChange(event.target.value)}><option>AM</option><option>PM</option></select></span></label>;
const EditAttendanceForm = ({ record, onClose, onSave }) => {
  const checkIn = toTimeParts(record.checkIn);
  const checkOut = toTimeParts(record.checkOut);
  const [values, setValues] = useState({ checkInTime: checkIn.time, checkInPeriod: checkIn.period, checkOutTime: checkOut.time, checkOutPeriod: checkOut.period, status: record.status });
  const workingHours = values.status === 'Absent' ? '0h 00m' : calculateWorkingHours(values.checkInTime, values.checkInPeriod, values.checkOutTime, values.checkOutPeriod);
  const setValue = (name, value) => setValues((current) => ({ ...current, [name]: value }));
  return <form className="p-5" onSubmit={(event) => { event.preventDefault(); onSave({ ...record, checkIn: values.status === 'Absent' ? '-' : `${values.checkInTime} ${values.checkInPeriod}`, checkOut: values.status === 'Absent' ? '-' : `${values.checkOutTime} ${values.checkOutPeriod}`, status: values.status, workingHours }); }}><div className="grid gap-4 sm:grid-cols-2"><TimeSelector label="Check In" time={values.checkInTime} period={values.checkInPeriod} onTimeChange={(value) => setValue('checkInTime', value)} onPeriodChange={(value) => setValue('checkInPeriod', value)} /><TimeSelector label="Check Out" time={values.checkOutTime} period={values.checkOutPeriod} onTimeChange={(value) => setValue('checkOutTime', value)} onPeriodChange={(value) => setValue('checkOutPeriod', value)} /><label className="text-sm font-medium text-[#344767]">Status<select className={fieldClassName} value={values.status} onChange={(event) => setValue('status', event.target.value)}><option>Present</option><option>Absent</option><option>Late</option></select></label><label className="text-sm font-medium text-[#344767]">Working Hours<input className={`${fieldClassName} cursor-not-allowed bg-[#f8fafc] text-[#667085]`} value={workingHours} readOnly /></label></div><footer className="mt-6 flex justify-end gap-3 border-t border-[#e7edf5] pt-5"><button className="rounded-md border border-[#dfe6f0] px-4 py-2.5 text-sm font-medium text-[#344767]" type="button" onClick={onClose}>Cancel</button><button className="rounded-md bg-[#4b3df2] px-4 py-2.5 text-sm font-medium text-white" type="submit">Save Changes</button></footer></form>;
};

const AttendanceRecordModal = ({ record, mode, isOpen, onClose, onSave }) => {
  if (!isOpen || !record) return null;
  const isEdit = mode === 'edit';
  const isTime = mode === 'time';
  const title = isEdit ? 'Edit Attendance' : isTime ? 'Attendance Time' : 'Attendance Details';

  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-[#101828]/45 p-4" role="dialog" aria-modal="true" aria-labelledby="attendance-modal-title"><section className="w-full max-w-lg rounded-xl bg-white shadow-2xl shadow-slate-900/25"><header className="flex items-center justify-between border-b border-[#e7edf5] px-5 py-4"><div><h2 id="attendance-modal-title" className="text-lg font-bold text-[#101828]">{title}</h2><p className="mt-1 text-xs text-[#667085]">{record.name} · {record.date}</p></div><button className="rounded-md p-2 text-[#667085] hover:bg-slate-100" type="button" onClick={onClose} aria-label="Close modal"><X size={20} /></button></header>{isEdit ? <EditAttendanceForm key={record.id} record={record} onClose={onClose} onSave={onSave} /> : <div className="p-5">{isTime ? <div className="rounded-lg bg-[#f8faff] p-5"><span className="flex size-11 items-center justify-center rounded-full bg-[#e7f1ff] text-[#2585f3]"><Clock3 size={22} /></span><div className="mt-4 grid grid-cols-2 gap-5"><Detail label="Check In" value={record.checkIn} /><Detail label="Check Out" value={record.checkOut} /><Detail label="Working Hours" value={record.workingHours} /><Detail label="Status" value={<AttendanceStatusBadge status={record.status} />} /></div></div> : <div className="grid grid-cols-2 gap-5"><Detail label="Employee ID" value={record.employeeId} /><Detail label="Department" value={record.department} /><Detail label="Designation" value={record.designation} /><Detail label="Date" value={record.date} /><Detail label="Check In" value={record.checkIn} /><Detail label="Check Out" value={record.checkOut} /><Detail label="Working Hours" value={record.workingHours} /><Detail label="Status" value={<AttendanceStatusBadge status={record.status} />} /></div>}<footer className="mt-6 flex justify-end border-t border-[#e7edf5] pt-5"><button className="rounded-md bg-[#4b3df2] px-4 py-2.5 text-sm font-medium text-white" type="button" onClick={onClose}>Close</button></footer></div>}</section></div>;
};

export default AttendanceRecordModal;
