import { Check, ChevronDown, Search, UserRound } from 'lucide-react';
import { useState } from 'react';
import Pagination from '../common/Pagination.jsx';
import AttendanceActions from './AttendanceActions.jsx';
import AttendanceStatusBadge from './AttendanceStatusBadge.jsx';

const headers = ['', '#', 'Employee ID', 'Employee Name', 'Department', 'Designation', 'Date', 'Check In', 'Check Out', 'Status', 'Working Hours', 'Actions'];

const AttendanceTable = ({ records, currentPage, pageSize, totalItems, onPageChange, onPageSizeChange, onView, onEdit, onTime, searchQuery, onSearchChange, selectedIds, onToggleRecord, onToggleAll, onBulkStatusChange }) => {
  const [isBulkMenuOpen, setIsBulkMenuOpen] = useState(false);
  const allVisibleSelected = records.length > 0 && records.every((record) => selectedIds.includes(record.id));
  const applyBulkStatus = (status) => { onBulkStatusChange(status); setIsBulkMenuOpen(false); };

  return (
  <section className="overflow-hidden rounded-xl border border-[#e4eaf2] bg-white shadow-[0_2px_8px_rgba(16,24,40,0.02)]">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e8edf4] px-4 py-4 sm:px-5"><h2 className="text-[13px] font-bold text-[#101828]">Attendance Records</h2><div className="flex flex-wrap items-center gap-3"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#526078]" size={14} /><input className="w-[230px] rounded-md border border-[#dfe6f0] py-2 pl-9 pr-3 text-[11px] text-[#101828] outline-none placeholder:text-[#667085] focus:border-[#6659f5]" type="search" placeholder="Search employee..." value={searchQuery} onChange={(event) => onSearchChange(event.target.value)} /></label><div className="relative"><button className="flex items-center gap-2 rounded-md border border-[#dfe6f0] px-3 py-2 text-[11px] font-medium text-[#101828] disabled:cursor-not-allowed disabled:text-[#98a2b3]" type="button" onClick={() => setIsBulkMenuOpen((isOpen) => !isOpen)} disabled={!selectedIds.length}>Bulk Actions <ChevronDown size={13} /></button>{isBulkMenuOpen && <div className="absolute right-0 z-20 mt-2 w-40 rounded-md border border-[#e4eaf2] bg-white p-1 shadow-lg"><p className="px-2 py-1 text-[10px] text-[#667085]">{selectedIds.length} selected</p>{['Present', 'Absent', 'Late'].map((status) => <button className="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-[11px] text-[#344767] hover:bg-slate-50" type="button" key={status} onClick={() => applyBulkStatus(status)}><Check size={13} />Mark {status}</button>)}</div>}</div></div></header>
    <div className="overflow-x-auto"><table className="w-full min-w-[1250px] border-collapse"><thead className="border-b border-[#e8edf4] bg-[#fbfcfe]"><tr>{headers.map((header) => <th className="whitespace-nowrap px-4 py-3 text-left text-[10px] font-semibold text-[#526078]" scope="col" key={header || 'select'}>{header || <input className="size-3.5 rounded border-[#b8c3d5]" type="checkbox" checked={allVisibleSelected} onChange={() => onToggleAll(records.map((record) => record.id))} aria-label="Select all attendance records" />}</th>)}</tr></thead><tbody>{records.map((record) => <tr className="border-b border-[#edf1f6] last:border-0 hover:bg-[#fafbff]" key={record.id}><td className="px-4 py-3"><input className="size-3.5 rounded border-[#b8c3d5]" type="checkbox" checked={selectedIds.includes(record.id)} onChange={() => onToggleRecord(record.id)} aria-label={`Select ${record.name}`} /></td><td className="px-4 py-3 text-[11px] text-[#101828]">{record.id}</td><td className="px-4 py-3 text-[11px] font-medium text-[#101828]">{record.employeeId}</td><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="flex size-7 items-center justify-center rounded-full text-white" style={{ backgroundColor: record.avatar }}><UserRound size={15} /></span><span className="whitespace-nowrap text-[11px] text-[#101828]">{record.name}</span></div></td><td className="px-4 py-3 text-[11px] text-[#101828]">{record.department}</td><td className="px-4 py-3 text-[11px] text-[#101828]">{record.designation}</td><td className="px-4 py-3 whitespace-nowrap text-[11px] text-[#101828]">{record.date}</td><td className={`px-4 py-3 whitespace-nowrap text-[11px] ${record.status === 'Late' ? 'text-[#f79009]' : record.status === 'Present' ? 'text-[#0a9d59]' : 'text-[#101828]'}`}>{record.checkIn}</td><td className={`px-4 py-3 whitespace-nowrap text-[11px] ${record.status === 'Present' ? 'text-[#f04438]' : 'text-[#101828]'}`}>{record.checkOut}</td><td className="px-4 py-3"><AttendanceStatusBadge status={record.status} /></td><td className="px-4 py-3 whitespace-nowrap text-[11px] text-[#101828]">{record.workingHours}</td><td className="px-4 py-3"><AttendanceActions record={record} onView={onView} onEdit={onEdit} onTime={onTime} /></td></tr>)}</tbody></table></div>
    <Pagination currentPage={currentPage} totalItems={totalItems} pageSize={pageSize} onPageChange={onPageChange} onPageSizeChange={onPageSizeChange} />
  </section>
  );
};

export default AttendanceTable;
